#!/usr/bin/env bash
# Render a Homebrew formula for the `sigil` + `sigil-config` CLI from the
# release tarballs package-cli.sh already built. Not published anywhere by
# this repo: it writes sigil.rb to an output path, and it is on Tom to copy
# that file into a tap repo (e.g. a new `rainnworks/homebrew-tap`, formula
# path `Formula/sigil.rb`) and push it - see docs/RELEASE.md.
#
# Usage: scripts/release/render-homebrew-formula.sh <version> <repo-slug> <out-file> <dist-dir>
#   scripts/release/render-homebrew-formula.sh v0.1.0 rainnworks/op-remote dist/sigil.rb dist
#
# <dist-dir> must already hold the two release tarballs' .sha256 files, as
# produced by package-cli.sh:
#   <dist-dir>/sigil-<version>-aarch64-apple-darwin.tar.gz.sha256
#   <dist-dir>/sigil-<version>-x86_64-apple-darwin.tar.gz.sha256
set -euo pipefail

if [[ $# -lt 4 ]]; then
  echo "usage: $0 <version> <repo-slug> <out-file> <dist-dir>" >&2
  exit 1
fi

VERSION="$1"
REPO_SLUG="$2"
OUT_FILE="$3"
DIST_DIR="$4"

ARM_SHA_FILE="$DIST_DIR/sigil-${VERSION}-aarch64-apple-darwin.tar.gz.sha256"
X86_SHA_FILE="$DIST_DIR/sigil-${VERSION}-x86_64-apple-darwin.tar.gz.sha256"

for f in "$ARM_SHA_FILE" "$X86_SHA_FILE"; do
  [[ -f "$f" ]] || { echo "missing $f - run package-cli.sh for both targets first" >&2; exit 1; }
done

ARM_SHA="$(awk '{print $1}' "$ARM_SHA_FILE")"
X86_SHA="$(awk '{print $1}' "$X86_SHA_FILE")"
VERSION_NUM="${VERSION#v}"

mkdir -p "$(dirname "$OUT_FILE")"
cat > "$OUT_FILE" <<EOF
# Generated by scripts/release/render-homebrew-formula.sh for ${VERSION}.
# Copy into a tap repo as Formula/sigil.rb - see docs/RELEASE.md.
class Sigil < Formula
  desc "Personal remote-approval CLI for 1Password and other gated secrets"
  homepage "https://github.com/${REPO_SLUG}"
  version "${VERSION_NUM}"

  on_arm do
    url "https://github.com/${REPO_SLUG}/releases/download/${VERSION}/sigil-${VERSION}-aarch64-apple-darwin.tar.gz"
    sha256 "${ARM_SHA}"
  end

  on_intel do
    url "https://github.com/${REPO_SLUG}/releases/download/${VERSION}/sigil-${VERSION}-x86_64-apple-darwin.tar.gz"
    sha256 "${X86_SHA}"
  end

  def install
    bin.install "sigil"
    bin.install "sigil-config"
  end

  test do
    system "#{bin}/sigil", "--version"
  end
end
EOF

echo "wrote $OUT_FILE"
